### ISSUE TITLE
Scroll the termanil in the browser

### ISSUE THREAD

**Issue by webmastak** [elisescu/tty-share#11]
Scrolling in the browser with the mouse brings up commands in the shell history.
When for example you execute the `ls -al` command, it is impossible to scroll up.
In the same [gotty](https://github.com/yudai/gotty) it is possible to scroll, which is very convenient with commands such as **ls**.

Also weird scaling of text in the browser. If you expand the terminal or switch to full-screen, the text becomes smaller than if you open the default terminal in size and run **tty-share**.

**Comment by webmastak** [comment]
The problem has not been resolved, the application loses all meaning without scrolling!

**Comment by elisescu** [comment]
I didn't get the chance to do that, @webmastak . 
As I mentioned in the PR, I don't think the scrolling toggle/option should be anywhere else but on the frontend side. Unfortunately, frontend development is not my strong side, and I won't be able to do it quickly enough.
But perhaps it makes sense to have it enabled by default (can't remember why I switched it off as default). I'll make a quick commit with that, and tag it. With the new architecture, the good side is this change will be on the tty-share command itself, and not on the server side.

**Comment by elisescu** [comment]
Done that here: https://github.com/elisescu/tty-share/releases/tag/v2.1.0
