### ISSUE TITLE
OSS-fuzz

### ISSUE THREAD

**Issue by teroz** [elisescu/tty-share#16]
Can i submit this project to [OSS-fuzz](https://github.com/google/oss-fuzz/) with a view of getting the binaries fuzzed? I would put you down as the engineering contact

**Comment by elisescu** [comment]
@teroz yes, definitely! Feel free to do so.
I am working on a new version now, which will soon get merged to master, just so you know.
https://github.com/elisescu/tty-share/tree/v2
