### ISSUE TITLE
Make only FIRST user to connect to the URL have control over tty

### ISSUE THREAD

**Issue by aweussom** [elisescu/tty-share#18]
I really need that subsequent connections are read-only

**Comment by elisescu** [comment]
The new v2.0.0 release supports read only sessions now. It is not really what you ask for, but you can achieve it by creating two sessions: first one read-write, and inside that one, create a new read-only and share with the rest of the users this read-only one.

**Comment by elisescu** [comment]
@aweussom 
The new v2.0.0 release supports read only sessions now. It is not really what you ask for, but you can achieve it by creating two sessions: first one read-write, and inside that one, create a new read-only and share with the rest of the users this read-only one.
