### ISSUE TITLE
Suppress "New connection from..."

### ISSUE THREAD

**Issue by aweussom** [elisescu/tty-share#19]
This messes up my terminal, and I'd rather not see it - it is used for displaying a monitoring page only.
No need to know how many/when someone connects (preferably read-only)

**Comment by elisescu** [comment]
@aweussom I pushed a new release with several new features, one of them being read only sessions. Have a look. The new version should not print when new connections happen. Let me know how it works

**Comment by elisescu** [comment]
Closing it for now. Please feel free to re-open if you see the issue again
