### ISSUE TITLE
Potential Augmentation

### ISSUE THREAD

**Issue by endzyme** [elisescu/tty-share#2]
Hi there! 

I am curious how difficult it would be to change the pty client from a websocket frontend to a go binary client? Instead of connecting to the session with a browser it would be nice functonality to `tty_receiver -server tty-share.elisescu.com:7654` and have an interactive terminal.

**Comment by elisescu** [comment]
@endzyme  - sorry for the very late reply. I completely missed this.
In theory shouldn't be difficult. In fact, I had this in mind when I tried to structure the code around the client/receiver side.
Maybe not so far in the future I will have time to get back to it, and add that functionality :)
