### ISSUE TITLE
Latest releases don't include binaries

### ISSUE THREAD

**Issue by matthewstrasiotto** [elisescu/tty-share#23]

**Comment by akhan4u** [comment]
Please include the binaries for the latest release!

**Comment by Blakeinstein** [comment]
So I guess the only option currently is to use the docker container?

**Comment by matthewstrasiotto** [comment]
@Blakeinstein 
> So I guess the only option currently is to use the docker container?

Not really, just building the binary using `go` is probably a better option, I find that usually setting up a `go` environment is straightforward enough (or use a `go` building container). 

Of course, ideally there'd be  binaries available via package managers + GH releases- I've noticed that @elisescu usually responds if you @ him or message him on twitter.

I'll build a binary & post a google drive link to this thread later today in the mean time, whether or not you trust whatever binary I give you is up to you, of course (I am a contributor on the project, if it helps lol)

**Comment by matthewstrasiotto** [comment]
@ some stage maybe I'll try to configure the github actions to automatically bundle a binary with releases, too

**Comment by matthewstrasiotto** [comment]
Drive link to binary built on WSL ubuntu, amd64 - https://drive.google.com/file/d/1YJM-hzp4fS91UIzRcZZfX8XFZDpP2SYB/view?usp=sharing
