### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by wallace11** [elisescu/tty-share#4]
Running `make out/tty-share` results in:
```
tty-share/pty_master.go:10:2: cannot find package "github.com/elisescu/pty" in any of:
        /usr/lib/go/src/github.com/elisescu/pty (from $GOROOT)
tty-share/main.go:14:2: cannot find package "github.com/elisescu/tty-share/common" in any of:
        /usr/lib/go/src/github.com/elisescu/tty-share/common (from $GOROOT)
```
I could probably fiddle with it to make it run but it looks like there's a step missing in the makefile.

**Comment by andres-ortiz** [comment]
go get github.com/elisescu/pty
go get github.com/elisescu/tty-share/common

**Comment by wallace11** [comment]
That fixed the problem! Thanks!

Maybe it'd be a good idea to add something to the readme?
