### ISSUE TITLE
Does not build on riscv64

### ISSUE THREAD

**Issue by nmeum** [elisescu/tty-share#40]
Hi, just wanted to let you know that tty-share does not build on riscv64 because you are using your own fork of [creack/pty](https://github.com/creack/pty) which does not support riscv64 yet. Have you considered switching to the upstream version?

```
go: downloading github.com/elisescu/pty v1.0.2
go: downloading github.com/moby/term v0.0.0-20200915141129-7f0af18e79f2
go: downloading golang.org/x/crypto v0.0.0-20191227163750-53104e6ec876
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/hashicorp/yamux v0.0.0-20200609203250-aecfd211c9ce
go: downloading github.com/gorilla/mux v1.8.0
go: downloading golang.org/x/sys v0.0.0-20200831180312-196b9ba8737a
# github.com/elisescu/pty
../../../../../go/pkg/mod/github.com/elisescu/pty@v1.0.2/pty_linux.go:34:8: undefined: _C_uint
../../../../../go/pkg/mod/github.com/elisescu/pty@v1.0.2/pty_linux.go:43:8: undefined: _C_int
```

**Comment by elisescu** [comment]
Hey @nmeum ! Thanks for letting me know.  I don't really have time to look into that this period, but I'll leave this open and maybe get back to it at some point. I think I needed a change in the pty module, hence the fork, but can't remember exactly what, and whether that's really needed. 
Feel free to send a PR if you want :)

**Comment by elisescu** [comment]
@nmeum this should be fixed with the latest release https://github.com/elisescu/tty-share/releases/tag/v2.4.0
