### ISSUE TITLE
gzip compressed data converted to hex format present in server/assets_bundle.go

### ISSUE THREAD

**Issue by fvcr** [elisescu/tty-share#51]
Hello @elisescu, 

I saw that on [server/assets_bundle.go](https://github.com/elisescu/tty-share/blob/e6bbaefd4708aff17c35aeba7f01c523935b91fb/server/assets_bundle.go) we have some compressed gzip files converted to hex format,
would it be possible to perform this conversion at build time instead of providing them in hex format?

I have been doing a comparison,
I convert the file in hex to gz and then open and compare to see if there is a difference between the files or not.

Would it make sense for you to generate these gz files at build time? 

Thanks a lot!

**Comment by elisescu** [comment]
Hi @fvcr! 

I think the compression is done at build-time (the time of building the assets_bundle.go file, not the frontend code - but there's no practical difference). 
I have not checked go-bindata in details, but at a quick glance over [server/assets_bundle.go](https://github.com/elisescu/tty-share/blob/e6bbaefd4708aff17c35aeba7f01c523935b91fb/server/assets_bundle.go), it looks like for reading the "files" (the bundled hex data), it uses a gzip reader, so the data part of those hex arrays must be compressed. And the compression must be done at built-time, when he assets_bundle.go file is generated. 

Or do I misunderstand what you meant?

**Comment by fvcr** [comment]
Hello,

I would like to generate this during the go build and no longer have assets_bundle.go.

I thought that we could create this assets_bundle.go file during the build of tty-share.

As I understand it this file is being created this way*:
```
go-bindata frontend/static/404.css \
           frontend/templates/404.in.html \
           frontend/static/bootstrap.min.css \
           frontend/templates/tty-share.in.html
```
*I could not find the file tty-share.js.

I could not generate the file like yours.

The version of go-bindata I am using:
```
go-bindata -version
go-bindata 3.1.0 (Go runtime go1.15.9).
Copyright (c) 2010-2013, Jim Teeuwen.
```

difference go-bindata output
[https://github.com/fvcr/tty-share/commit/629255209a072cf4140e8f26fdfc35a278172d28](https://github.com/fvcr/tty-share/commit/629255209a072cf4140e8f26fdfc35a278172d28)

Thanks!

**Comment by elisescu** [comment]
Have a look at the [Makefile](https://github.com/elisescu/tty-share/blob/master/server/Makefile) - that's the script calling go-bindata and creating the `assets_budnle.go`. `tty-share.js` is built from the `server/frontend/**` source files, but it's not committed to git. Anyways, the Makefile should help you understand how everything is built.

**Comment by fvcr** [comment]
Ok, thanks!
