### ISSUE TITLE
Connection refused to localhost on any port.

### ISSUE THREAD

**Issue by YellowOnion** [elisescu/tty-share#54]
```
> tty-share  --readonly --command tmux --args "attach -t default --ignore-size" --public
public session: https://on.tty-share.com/s/<snip />/
local session: http://localhost:8000/s/local/
Press Enter to continue!
ERRO[0005] Cannot proxy the connection to the target HTTP server: dial tcp [::1]:8000: connect: connection refused
```

I've tried multiple ports...do I need to run tty-server manually? Both local and remote don't work.

I'm confused what I'm supposed to do.

**Comment by YellowOnion** [comment]
Okay I seemed to get it working, pressing enter actually drops me in to a bash shell and I thought it quit the app, I could then join the session, I still get the error even on ipv4 and a different port, but I just don't understand what it means, since it seems to be working both publically and locally, when I actually hit enter.

**Comment by elisescu** [comment]
@YellowOnion that's pretty weird, and I have no idea why you get that message, and even more so why it works given the message. According to the message, it should not work - as it can't connect to the "server" (local) that runs the actual session (and serves the frontend + websockets). Sorry but I have no clue what's going on there

**Comment by elisescu** [comment]
@YellowOnion I am closing this issue. Feel free to re-open it if you have more questions
