### ISSUE TITLE
[Feature Request] Add an option to disable input/view only

### ISSUE THREAD

**Issue by chavinlo** [elisescu/tty-share#56]
It would be nice to have this feature so we can share the terminal to a large audience without having chaos

**Comment by elisescu** [comment]
@chavinlo  that should already be possible with the `-readonly` option. Or is it something else you're looking for?

**Comment by chavinlo** [comment]
> @chavinlo that should already be possible with the `-readonly` option. Or is it something else you're looking for?
Ah, sorry. I didn't see that.
