### ISSUE TITLE
Build: need symlink

### ISSUE THREAD

**Issue by aweussom** [elisescu/tty-share#8]
git clone https://github.com/elisescu/tty-share.git
cd tty-share
cd frontend
nvm use
npm install
npm run build # builds the frontend
cd -
make all

"make all" will fail. You need to symlink in the tty-share dir in the elisescu subdir:
user@hostname:~$ ls -alrt go/src/github.com/elisescu/
lrwxrwxrwx 1 username domain users   22 Nov 19 16:14 tty-share -> /home/username/tty-share

**Comment by elisescu** [comment]
This should be fixed now, with the new version? Closing it for now, but please re-open if you see it still failing on your side.
