### ISSUE TITLE
go-bindata

### ISSUE THREAD

**Issue by aweussom** [elisescu/tty-share#9]
On Ubuntu 18.04 go-bindata is not installed.
sudo apt-get install go-bindata

fixes it, but I think it would be better/easier if the build-script pulled it with the other dependencies?

**Comment by elisescu** [comment]
I haven't looked very closely, but at first sight it looks like go-bindata is a binary, and the go modules doesn't install that properly. It should be pulled by the [Makefile](https://github.com/elisescu/tty-share/blob/master/server/Makefile#L11) when needed though.
If you know of a better way, I would be happy to do it, so please re-open if so :)
